env: "local" # dev, prod
storage_path: "./storage/sso.db"
token_ttl: 1h

postgres:
  dsn: "postgres://user:pass@postgres:5432/sso?sslmode=disable" # если запускать Go на VM, то вместо @postgres используем @localhost
  max_open_conns: 20
  max_idle_conns: 5

redis:
  addr: "redis:6379" # если Go на VM, то используем "localhost:6379"; иначе "redis:6379" из контейнера
  db: 0

grpc:
  port: 44044
  timeout: 10h

http:
  port: 8080
  cors_allowed_origins: ["http://localhost:5173"]

tls:
  cert_file: "./certs/localhost.crt"
  key_file: "./certs/localhost.key"